-- local mapFolder = workspace.Map

-- local stage1 = mapFolder.Stage1

-- local stage1Part: Part = stage1.Stage1Part

-- local stage1Pos: Vector3 = stage1Part.Position

-- local multiple: number = 0.35
-- local function stage1Load()
--     for i = 1,25 do
--         local newPart = stage1Part:Clone()
--         local newPartPos = stage1Pos + Vector3.new(0,0,stage1Pos.Z* i * multiple)
--         newPart.Position = newPartPos
--         newPart.Parent = stage1
--         multiple = multiple + 0.04
--      --  stage1Pos = newPartPos
--     end

-- end



-- stage1Load()